resources:
  - ../base
components:
  # pod-updater is required if status-labels or in-place-scaling is enabled
  - ../pod-updater
  - ../status-labels
  # uncommment to enable in-place-scaling
  # - ../in-place-scaling
images:
  - name: manager
    newName: ghcr.io/ctrox/zeropod-manager
    newTag: v0.3.1
  - name: installer
    newName: ghcr.io/ctrox/zeropod-installer
    newTag: v0.3.1
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/args/-
        value: -criu-image=ghcr.io/ctrox/zeropod-criu:v3.19
    target:
      kind: DaemonSet
