name: ci

on: [push]

jobs:
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false
          version: "2023.1.6"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: test
        run: sudo --preserve-env make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: protobuf-compiler libprotobuf-dev
          version: 1.0

      - name: build ebpf image
        run: make build-ebpf

      - name: generate ttrpc and ebpf
        run: make generate

      - name: check for diff
        run: git diff --exit-code

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: e2e
        run: make test-e2e
